title: APEX
permalink: ':title/'
email: apexdiabolo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Apex Diabolo Performance Group
baseurl: "" # the subpath of your site, e.g. /blog
url: ""

sass:
  sass_dir: assets/css/scss

plugins:
  - jekyll-redirect-from
